### PR TITLE
Clarify RVM instructions

### PR DESCRIPTION
**Pull request by bengolder**
Explain a bit more about how RVM is used.

### CODE REVIEW

**Comment by daguar** [comment]
Thanks!

**Comment by migurski** [comment]
This is pretty detailed—I wonder if there’s already an equivalent set of docs on the RVM site that we can quote or link to?

**Comment by migurski** [comment]
…motivation being that we shouldn’t duplicate too much here, just the bare minimum to ensure that someone is following the right authoritative directions. Samples [for `pip`](https://github.com/codeforamerica/howto/blob/master/Python-Virtualenv.md#pip) and [PostgreSQL](https://github.com/codeforamerica/howto/blob/master/PostgreSQL.md#installation).

**Comment by bengolder** [comment]
@migurski I found it hard to find info on typical use of RVM on their website (hence why I asked on #techteam). If I could find concise instructions on typical use, I think it would be better to link to them. Here are the best two candidates:https://rvm.io/workflow/examples

**Comment by migurski** [comment]
Ah, if there isn’t an obvious candidate then this is probably fine. I’d love to avoid writing too much if it can fall out of date.

**Pull request merged**
